name: 'ci'

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev

  pull_request:

permissions:
  contents: write
  pull-requests: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest src tests --doctest-modules --cov=src --cov-report=xml:./reports/coverage/coverage.xml

      - name: Prepare coverage badge generation
        run: |
          pip install genbadge[all]

      - name: Generate coverage badge
        # if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          genbadge coverage -o ./badges/coverage.svg

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false

      - name: Deploy Badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges [skip ci]"
          branch: gh-pages
          skip_fetch: true
          skip_checkout: true
          file_pattern: badges/*

      # Without this, will get Error:
      # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/coverage-badge-action/coverage-badge-action/action.yml'.
      # Did you forget to run actions/checkout before running your local action?
      - name: Checkout Back
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
